# Generated by Django 2.1.4 on 2018-12-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=243)),
                ('lname', models.CharField(max_length=243)),
                ('email', models.EmailField(max_length=243, unique=True)),
                ('Address', models.CharField(max_length=243)),
            ],
        ),
    ]
