# Generated by Django 2.1.4 on 2019-01-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190103_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_model',
            name='remark',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
