# Generated by Django 2.1.4 on 2019-01-04 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190104_0729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_model',
            old_name='remark',
            new_name='key',
        ),
    ]
