# Generated by Django 2.1.4 on 2019-01-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_model',
            old_name='file_name',
            new_name='file',
        ),
    ]
